force-app/main/default/objects/Charge__c/Charge__c.object-meta.xml
<CustomObject>
    <label>Charge</label>
    <nameField>
        <label>Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Charge__c/fields/Contact_Id__c.field-meta.xml
<CustomField>
    <fullName>Contact_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Id</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Charges</relationshipLabel>
    <relationshipName>Charges</relationshipName>
    <type>Lookup</type>
</CustomField>
 

force-app/main/default/objects/Charge__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <label>End Time</label>
    <type>DateTime</type>
</CustomField>
 

force-app/main/default/objects/Charge__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <label>Start Time</label>
    <type>DateTime</type>
</CustomField>
 

force-app/main/default/objects/Contact/fields/Card_Value__c.field-meta.xml
<CustomField>
    <fullName>Card_Value__c</fullName>
    <label>Card Value</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>
 

force-app/main/default/classes/SendAmountDueDetails_Test.cls
@isTest
public class SendAmountDueDetails_Test {

    public static testMethod void validatesendEmail() {
        List<Contact> con = new List<Contact>();
        Contact c = new Contact();
        c.LastName = 'Test';
        c.Card_Value__c = 100;
        c.Email = 'abc@test.com';
        con.add(c);
        insert con;
        SendAmountDueDetails.sendEmail(con);
    }
    
    public static testMethod void validateTriggerUpdate() {
        Contact c = new Contact();
        c.LastName = 'Test';
        c.Card_Value__c = 100;
        c.Email = 'abc@test.com';
        insert c;
        
        Charge__c ch = new Charge__c();
        ch.Name = 'Test';
        ch.Contact_Id__c = c.Id;
        ch.Start_Time__c = System.now();
        insert ch;
        
        ch.End_Time__c = System.now();
        update ch;
    }
}