force-app/main/default/objects/Charge__c/Charge__c.object-meta.xml
<CustomObject>
    <label>Charge</label>
    <nameField>
        <label>Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Charge__c/fields/Contact_Id__c.field-meta.xml
<CustomField>
    <fullName>Contact_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Id</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Charges</relationshipLabel>
    <relationshipName>Charges</relationshipName>
    <type>Lookup</type>
</CustomField>
 

force-app/main/default/objects/Charge__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <label>End Time</label>
    <type>DateTime</type>
</CustomField>
 

force-app/main/default/objects/Charge__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <label>Start Time</label>
    <type>DateTime</type>
</CustomField>
 

force-app/main/default/classes/RecordInsertion.cls
public class RecordInsertion
{

    @AuraEnabled
    public static void createChargeRecord(Id recordId){
        System.debug('recordId>>'+recordId);
        List<Charge__c> charge = new List<Charge__c>();
            Charge__c c = new Charge__c();
            c.Start_Time__c = System.now();
            c.Contact_Id__c = recordId;
            charge.add(c); 
        if(charge.size() > 0){
            insert charge;
        }
    }    
    
    @AuraEnabled
    public static void updateEndTime(Id recordId){
            Charge__c c = [select id,lastmodifieddate from Charge__c where Contact_Id__c =: recordId order by lastmodifieddate desc limit 1];
            System.debug('charge record to update>>'+c);
                c.End_Time__c = System.now(); 
        if(c != null){
            update c;
        }
    } 
}